name: Run Workflows
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call-npm-publish:
    uses: ./.github/workflows/npm-publish-github-packages.yml
permissions:
  packages: write
  contents: read